---
title: "APM466a1"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(readxl)
library(jrvFinance)

```



```{r}
bond_data <- read_excel("APM466/APM466 A1 data.xlsx",sheet=3)
coupon <- bond_data$Coupon
maturity_date <- bond_data$`Maturity Date`
price_date <- c("2023-1-16","2023-1-17","2023-1-18","2023-1-19","2023-1-20","2023-1-23","2023-1-24","2023-1-25","2023-1-26","2023-1-27")
price_matrix <- matrix(c(bond_data$"16",bond_data$"17",bond_data$"18",bond_data$"19",bond_data$"20",bond_data$"23",bond_data$"24",bond_data$"25",bond_data$"26",bond_data$"27"),nrow=10,ncol = 10,byrow = TRUE)
```

```{r}
ytm_matrix <- matrix("numeric",nrow = 10, ncol = 10)
for (i in c(1:10)){
  for (j in c(1:10)) {
    ytm_matrix[i,j] <- bond.yield(price_date[i],
                        maturity_date[j],
                        coupon[j],
                        freq = 2,
                        price_matrix[i,j],
                        convention = c("30/360", "ACT/ACT", "ACT/360", "30/360E"),
                        comp.freq = 2,
                        redemption_value = 100) } }
```


```{r}
dirty_price_matrix <- matrix("numeric",nrow = 10, ncol = 10)
for (i in c(1:10)){
  for (j in c(1:10)) {
    dirty_price_matrix[i,j] <- bond.TCF(price_date[i],
                        maturity_date[j],
                        coupon[j],
                        freq = 2,
                        convention = c("30/360", "ACT/ACT", "ACT/360", "30/360E"),
                        redemption_value = 100)$accrued + price_matrix[i,j]}}
```


```{r}
for (i in c(1:10)){
  cash_flow <- bond.TCF(price_date[i],
       maturity_date[i],
       coupon[i],
       freq = 2,
       convention = c("30/360", "ACT/ACT", "ACT/360", "30/360E"),
       redemption_value = 100)$cf
  assign(paste0("cash_flow_",i), cash_flow)
}
```



```{r}
year_fraction_matrix <- matrix("numeric",nrow = 10, ncol = 10)
for (i in c(1:10)){
  for (j in c(1:10)) {
    year_fraction_matrix[i,j] <- yearFraction(
                                   price_date[i],
                                   maturity_date[j],
                                   freq = 2,
                                   convention = c("30/360", "ACT/ACT", "ACT/360", "30/360E"))}}
```

```{r}
year <- c(0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)
plot(year, ytm_matrix[1,], main = "Yield Curve", xlab = "Year", ylab = "YTM", type = "o", col = "black")

colors <- c("red", "orange", "yellow", "green", "pink", "blue", "purple", "pink", "brown")
for (i in 2:10) {
points(year, ytm_matrix[i,], type = "o", col = colors[i - 1])
lines(year, ytm_matrix[i,], type = "o", col = colors[i - 1])
}
```

```{r}
spot_matrix <- matrix(nrow=10,ncol = 10)
for (i in 1:10){
  t1 <- as.numeric(year_fraction_matrix[i,1])
  sf1 <- function(x) as.numeric(dirty_price_matrix[i,1])-cash_flow_1[1]*(1+x/2)^(-2*t1)
  s1 <- uniroot(sf1,c(0,1))$root
  
  t2 <- as.numeric(year_fraction_matrix[i,2])
  sf2 <- function(x) as.numeric(dirty_price_matrix[i,2])-cash_flow_2[1]*(1+s1/2)^(-2*(t2-0.5*1))-cash_flow_2[2]*(1+x/2)^(-2*t2)
  s2 <- uniroot(sf2,c(0,1))$root
  
  
  t3 <- as.numeric(year_fraction_matrix[i,3])
  sf3 <- function(x) as.numeric(dirty_price_matrix[i,3])-cash_flow_3[1]*(1+s1/2)^(-2*(t3-0.5*2))-cash_flow_3[2]*(1+s2/2)^(-2*(t3-0.5*1))-cash_flow_3[3]*(1+x/2)^(-2*t3)
  s3 <- uniroot(sf3,c(0,1))$root
  
  
  t4 <- as.numeric(year_fraction_matrix[i,4])
  sf4 <- function(x) as.numeric(dirty_price_matrix[i,3])-cash_flow_4[1]*(1+s1/2)^(-2*(t4-0.5*3))-cash_flow_4[2]*(1+s2/2)^(-2*(t4-0.5*2))-cash_flow_4[3]*(1+s3/2)^(-2*(t4-0.5*1))-cash_flow_4[4]*(1+x/2)^(-2*t4)
  s4 <- uniroot(sf4,c(0,1))$root
  
  t5 <- as.numeric(year_fraction_matrix[i,5])
  sf5 <- function(x) as.numeric(dirty_price_matrix[i,3])-cash_flow_5[1]*(1+s1/2)^(-2*(t5-0.5*4))-cash_flow_5[2]*(1+s2/2)^(-2*(t5-0.5*3))-cash_flow_5[3]*(1+s3/2)^(-2*(t5-0.5*2))-cash_flow_5[4]*(1+s4/2)^(-2*(t5-0.5*1))-cash_flow_5[5]*(1+x/2)^(-2*t5)
  s5 <- uniroot(sf5,c(0,1))$root
  
  t6 <- as.numeric(year_fraction_matrix[i,6])
  sf6 <- function(x) as.numeric(dirty_price_matrix[i,3])-cash_flow_6[1]*(1+s1/2)^(-2*(t5-0.5*5))-cash_flow_6[2]*(1+s2/2)^(-2*(t6-0.5*4))-cash_flow_6[3]*(1+s3/2)^(-2*(t6-0.5*3))-cash_flow_6[4]*(1+s4/2)^(-2*(t6-0.5*2))-cash_flow_6[5]*(1+s5/2)^(-2*(t6-0.5*1))-cash_flow_6[6]*(1+x/2)^(-2*t6)
  s6 <- uniroot(sf6,c(0,1))$root
  
  
  t7 <- as.numeric(year_fraction_matrix[i,7])
  sf7 <- function(x) as.numeric(dirty_price_matrix[i,3])-cash_flow_7[1]*(1+s1/2)^(-2*(t7-0.5*6))-cash_flow_7[2]*(1+s2/2)^(-2*(t7-0.5*5))-cash_flow_7[3]*(1+s3/2)^(-2*(t7-0.5*4))-cash_flow_7[4]*(1+s4/2)^(-2*(t7-0.5*3))-cash_flow_7[5]*(1+s5/2)^(-2*(t7-0.5*2))-cash_flow_7[6]*(1+s6/2)^(-2*(t7-0.5*1))-cash_flow_7[7]*(1+x/2)^(-2*t7)
  s7 <- uniroot(sf7,c(0,1))$root
  
  
  t8 <- as.numeric(year_fraction_matrix[i,8])
  sf8 <- function(x) as.numeric(dirty_price_matrix[i,3])-cash_flow_8[1]*(1+s1/2)^(-2*(t8-0.5*7))-cash_flow_8[2]*(1+s2/2)^(-2*(t8-0.5*6))-cash_flow_8[3]*(1+s3/2)^(-2*(t8-0.5*5))-cash_flow_8[4]*(1+s4/2)^(-2*(t8-0.5*4))-cash_flow_8[5]*(1+s5/2)^(-2*(t8-0.5*3))-cash_flow_8[6]*(1+s6/2)^(-2*(t8-0.5*2))-cash_flow_8[7]*(1+s7/2)^(-2*(t8-0.5*1))-cash_flow_8[8]*(1+x/2)^(-2*t8)
  s8 <- uniroot(sf8,c(0,1))$root
  
  
  t9 <- as.numeric(year_fraction_matrix[i,9])
  sf9 <- function(x) as.numeric(dirty_price_matrix[i,3])-cash_flow_9[1]*(1+s1/2)^(-2*(t9-0.5*8))-cash_flow_9[2]*(1+s2/2)^(-2*(t9-0.5*7))-cash_flow_9[3]*(1+s3/2)^(-2*(t9-0.5*6))-cash_flow_9[4]*(1+s4/2)^(-2*(t9-0.5*5))-cash_flow_9[5]*(1+s5/2)^(-2*(t9-0.5*4))-cash_flow_9[6]*(1+s6/2)^(-2*(t9-0.5*3))-cash_flow_9[7]*(1+s7/2)^(-2*(t9-0.5*2))-cash_flow_9[8]*(1+s8/2)^(-2*(t9-0.5*1))-cash_flow_9[9]*(1+x/2)^(-2*t9)
  s9 <- uniroot(sf9,c(0,1))$root
  
  t10 <- as.numeric(year_fraction_matrix[i,10])
  sf10 <- function(x) as.numeric(dirty_price_matrix[i,10])-cash_flow_10[1]*(1+s1/2)^(-2*(t10-0.5*9))-cash_flow_10[2]*(1+s2/2)^(-2*(t10-0.5*8))-cash_flow_10[3]*(1+s3/2)^(-2*(t10-0.5*7))-cash_flow_10[4]*(1+s4/2)^(-2*(t10-0.5*6))-cash_flow_10[5]*(1+s5/2)^(-2*(t10-0.5*5))-cash_flow_10[6]*(1+s6/2)^(-2*(t10-0.5*4))-cash_flow_10[7]*(1+s7/2)^(-2*(t10-0.5*3))-cash_flow_10[8]*(1+s8/2)^(-2*(t10-0.5*2))-cash_flow_10[9]*(1+s9/2)^(-2*(t10-0.5*1))-cash_flow_10[10]*(1+x/2)^(-2*t10)
  s10 <- uniroot(sf10,c(0,1))$root
  
   s <- rbind(s1,s2,s3,s4,s5,s6,s7,s8,s9,s10)
   spot_matrix[i,] <- s}

```



```{r}
year <- c(0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)
plot(year, spot_matrix[1,], main = "Spot Curve", xlab = "Year", ylab = "Spot", type = "o", col = "black")

colors <- c("red", "orange", "yellow", "green", "pink", "blue", "purple", "pink", "brown")
for (i in 2:10) {
 points(year, spot_matrix[i,], type = "o", col = colors[i - 1])
 lines(year, spot_matrix[i,], type = "o", col = colors[i - 1])}
```

```{r}
long_t <- c(yearFraction("2023-09-01","2024-03-01"),yearFraction("2024-09-01","2025-03-01"),yearFraction("2025-09-01","2026-03-01"),yearFraction("2026-09-01","2027-03-01"),yearFraction("2027-09-01","2028-03-01"))
short_t <- c(yearFraction("2023-09-01","2024-01-29"),yearFraction("2024-09-01","2025-01-29"),yearFraction("2025-09-01","2026-01-29"),yearFraction("2026-09-01","2027-01-29"),yearFraction("2027-09-01","2028-01-29"))
```

```{r}
est_spots <- list()
for (j in 1:10) {
spot_sep <- c(spot_matrix[j,][2],spot_matrix[j,][4],spot_matrix[j,][6],spot_matrix[j,][8],spot_matrix[j,][10])
spot_mar <- c(spot_matrix[j,][1],spot_matrix[j,][3],spot_matrix[j,][5],spot_matrix[j,][7],spot_matrix[j,][9])
est_spot <- spot_sep + (spot_mar - spot_sep)*(short_t/long_t)
est_spots[[j]] <- est_spot
}
names(est_spots) <- paste0("est_spot_", 1:10)
est_spot_all <- rbind(est_spot_1,est_spot_2,est_spot_3,est_spot_4,est_spot_5,est_spot_6,est_spot_7,est_spot_8,est_spot_9,est_spot_10)

```

```{r}
forward_matrix <- matrix(nrow = 10, ncol = 4)
for (j in c(1:10)){
  for (i in c(1:4)){
    forward <- function(x) ((1+est_spot_all[j,1]/2)^2)*((1+x/2)^(2*i))-(1+est_spot_all[j,i+1]/2)^(2*(i+1))
    forward_matrix[j,i] <- uniroot(forward,c(-1,1))$root
  }
}
forward_matrix
```

```{r}
year <- c(2,3,4,5)
plot(year, forward_matrix[1,], main = "Forward Curve", xlab = "Year", ylab = "Forward rate", type = "o", col = "black")

colors <- c("red", "orange", "yellow", "green", "pink", "blue", "purple", "pink", "brown")
for (i in 2:10) {
 points(year, forward_matrix[i,], type = "o", col = colors[i - 1])
 lines(year, forward_matrix[i,], type = "o", col = colors[i - 1])}
```
```{r}
ytm_matrix_2 <- matrix(nrow = 10, ncol =5)
for (i in 1:10){
ytm_matrix_2[i,1] <- est_spot_all[i,1]
for (j in 2:5){
ytm_matrix_2[i,j] <- as.numeric(ytm_matrix[i,(j-1)*2]) + (as.numeric(ytm_matrix[i,(j-1)*2+1]) - as.numeric(ytm_matrix[i,(j-1)*2])) * short_t[j] / long_t[j]
}
}
ytm_matrix_2
```

```{r}
log_ytm_matrix <- matrix(nrow = 9, ncol =5)
for (i in c(1:5)){
  for (j in c(1:9)){
    log_ytm_matrix[j,i] <- log(ytm_matrix_2[(j+1),i]/ytm_matrix_2[j,i])
  }}
log_ytm_matrix
```

```{r}
ytm_cov_matrix <- cov(log_ytm_matrix,log_ytm_matrix)
ytm_cov_matrix
```

```{r}
eigenvlues_ytm_cov <- eigen(ytm_cov_matrix)$values
eigenvectors_ytm_cov <- eigen(ytm_cov_matrix)$vectors
eigenvlues_ytm_cov
eigenvectors_ytm_cov
```

```{r}
log_forward_matrix <- matrix(nrow = 9, ncol =4)
for (i in c(1:4)){
  for (j in c(1:9)){
    log_forward_matrix[j,i] <- log(forward_matrix[(j+1),i]/forward_matrix[j,i])
  }}
log_forward_matrix
```

```{r}
forward_cov_matrix <- cov(log_forward_matrix,log_forward_matrix)
forward_cov_matrix
```

```{r}
eigenvlues_forward_cov <- eigen(forward_cov_matrix)$values
eigenvectors_forward_cov <- eigen(forward_cov_matrix)$vectors
eigenvlues_forward_cov
eigenvectors_forward_cov
```


